### ISSUE TITLE
Crest events

### ISSUE THREAD

**Issue by Hootyoo** [proxytranslation/user-docs#52]
We should probably describe all of the events that Crest emits: 

- crestDocumentTranslationStart
- crestDocumentTranslationEnd
- crestMissingTranslationStart
- crestMissingTranslationEnd
- crestMutationTranslationStart
- crestMutationTranslationEnd

**Comment by zmeggyesi** [comment]
https://proxytranslation.readthedocs.io/en/latest/tech-manual/crest.html#interop
Are they not?

**Comment by Hootyoo** [comment]
I forgot that. I guess this is a non-issue then.
